/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iad.ui;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 *
 * @author PiotrGrzelak
 */
public class IADFrame extends javax.swing.JFrame {

    private TransformationDialog transformationDialog;
    
    private ClassificationDialog classificationDialog;
    
    private ApproximationDialog approximationDialog;
    
    private ExecutorService executor;
    
    /**
     * Creates new form IADFrame
     */
    public IADFrame() {
        initComponents();
        transformationDialog = new TransformationDialog(this, true);
        classificationDialog = new ClassificationDialog(this, true);
        approximationDialog = new ApproximationDialog(this, true);
        executor = Executors.newCachedThreadPool();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transformationButton = new javax.swing.JButton();
        approximationButton = new javax.swing.JButton();
        classificationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IAD Zadanie 1");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        transformationButton.setText("Transformacja");
        transformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transformationButton, new java.awt.GridBagConstraints());

        approximationButton.setText("Aproksymacja");
        approximationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approximationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(approximationButton, new java.awt.GridBagConstraints());

        classificationButton.setText("Klasyfikacja");
        classificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classificationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(classificationButton, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformationButtonActionPerformed
        transformationDialog.setVisible(true);
    }//GEN-LAST:event_transformationButtonActionPerformed

    private void approximationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approximationButtonActionPerformed
        approximationDialog.setVisible(true);
    }//GEN-LAST:event_approximationButtonActionPerformed

    private void classificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classificationButtonActionPerformed
        classificationDialog.setVisible(true);
    }//GEN-LAST:event_classificationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IADFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IADFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IADFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IADFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IADFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approximationButton;
    private javax.swing.JButton classificationButton;
    private javax.swing.JButton transformationButton;
    // End of variables declaration//GEN-END:variables
}
