/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iad.ui;

import java.awt.Color;
import java.awt.GridLayout;

/**
 *
 * @author PiotrGrzelak
 */
public class ClassificationMatrixDialog extends javax.swing.JDialog {

    private MatrixTile[][] matrixView;

    /**
     * Creates new form ClassificationMatrixDialog
     */
    public ClassificationMatrixDialog(java.awt.Frame parent, int[][] classificationMatrix) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        
        int rows = classificationMatrix.length + 1;
        int columns = classificationMatrix[0].length + 1;
        matrixView = new MatrixTile[rows][columns];
        this.setSize(MatrixTile.TILE_WIDTH * columns, MatrixTile.TILE_HEIGHT * rows);

        GridLayout gridLayout = new GridLayout(rows, columns);
        this.setLayout(gridLayout);
        for (int i = 0; i < rows; ++i) {
            for (int j = 0; j < columns; ++j) {
                if (i == 0 && j == 0) {
                    matrixView[i][j] = new MatrixTile(-1, Color.DARK_GRAY);
                } else if (i == 0 && j != 0) {
                    matrixView[i][j] = new MatrixTile(j, Color.lightGray);
                } else if (j == 0 && i != 0) {
                    matrixView[i][j] = new MatrixTile(i, Color.GRAY);
                } else {
                    matrixView[i][j] = new MatrixTile(classificationMatrix[i - 1][j - 1], Color.WHITE);
                }
                this.add(matrixView[i][j]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Macierz klasyfikacji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
